config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'main#home'

  get 'about', to: 'main#about'

  get 'subject', to: 'main#subject'
  get 'another_subject', to: 'main#another_subject'
  get 'another_another_subject', to: 'main#another_another_subject'

  resources :users, only: [:index, :show, :edit, :update, :destroy]

  patch 'users/:id/update', to: 'users#reactivate_user', as: 'reactivate_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:student, :guardian, :teacher, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :student
  end

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  paginates_per 5

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

# provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  def gravatar
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @current_page = 'homepage'
  end

  def about
    @current_page = 'aboutpage'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # Soft DELETE resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  private
    def sign_up_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :current_password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :authorize_admin

  def index
    @users_count = User.count
    @users_by_roles = User.group(:role).order(:role).count
    @deleted_users_count = User.where.not(deleted_at: nil).count

    if params[:term] && !params[:term].empty?
      @users = User.where("name like :search or email like :search", search: "%#{params[:term]}%").order(id: :desc).page(params[:page])
    else
      if params[:deleted_at]
        @users = User.where.not(deleted_at: nil).order(id: :desc).page(params[:page])
      else
        if params[:role] && !params[:role].empty?
          @users = User.where(role: params[:role]).order(id: :desc).page(params[:page])
        else
          @users = User.order(id: :desc).page(params[:page])
        end
      end
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update_attributes(user_params)
     flash[:success] = "User updated successfully."
     redirect_to @user
   else
     render 'edit'
   end
  end

  def destroy
   @user = User.find(params[:id])
   if @user.destroy
     redirect_to users_url, notice: "User deleted."
   end
  end

  def reactivate_user
      @user = User.find(params[:id])
      if @user.update_attribute(:deleted_at, nil)
        flash[:success] = "User reactivated successfully."
        redirect_to @user
      else
        render 'edit'
      end
    end


  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :role)
    end

    def authorize_admin
      if current_user.role.nil? || current_user.role.to_sym != :admin
        flash[:alert] = "Not Authorized!"
        redirect_to root_url
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!

    return "" unless devise_error_messages?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML

    <div id="error_explanation" class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>

    HTML
    html.html_safe

  end
  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="row-fluid">
        <%= "Smashin Academy for Learning English"%>
        <% if user_signed_in? %>
          Signed in as <strong><%= current_user.email %></strong>
            <% if current_user.try(:admin?) %>
                Account Type: <strong>Admin</strong>
            <% else %>
                Account Type: <strong><%= current_user.role %></strong>
            <% end %>
        <% else %>
          Not Signed in
        <% end %>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <img src="/assets/Logo-1.jpg" width="30" height="30" class="d-inline-block align-top" alt="">
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>

      <li>
        <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  User
              </a>

              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete', class: 'nav-link' %>
                  <%= link_to 'Edit User Profile', edit_user_registration_path, class: 'nav-link' %>
              </div>
            </li>

            <% if current_user.role && current_user.role.to_sym == :admin %>
              <li class="nav-item">
                <%= link_to 'Users', users_path, class: 'nav-link' %>
              </li>
            <% end %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Subjects
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Subject', subject_path, class: 'dropdown-item' %>
                <%= link_to 'Another subject', another_subject_path, class: 'dropdown-item' %>
                <%= link_to 'Another another subject', another_another_subject_path, class: 'dropdown-item' %>
              </div>
            </li>

            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'  %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </li>

    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="/assets/wizard-3.png" type="image/x-icon" />
    <title>Smashin</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  </head>

  <body class="body
              <%= case @current_page
                  when 'homepage' then 'homepage'
                  when 'aboutpage' then 'aboutpage'
                  else ''
              end %> " >
    <div id="wrap">
      <%= render 'layouts/navigation' %>

      <div id="main" class="container-fluid clear-top">

        <% if notice %>
          <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= notice %>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= alert %>
          </div>
        <% end %>

        <div id="push">
          <%= yield %>
        </div>

      </div>
    </div>
  </body>

  <footer class="footer">
    <%= render 'layouts/footer' %>
  </footer>

</html>

app/views/main/about.html.erb
<h1>About Info</h1>

app/views/main/another_another_subject.html.erb
<h1>Another Another Subject</h1>

app/views/main/another_subject.html.erb
<h1>Another Subject</h1>

app/views/main/home.html.erb
<h1>Home Page</h1>

app/views/main/subject.html.erb
<h1>Subject</h1>

app/views/users/_show.html.erb
<div class="container-fluid">
  <table class="table table-striped table-hover">
    <tbody>
      <tr class="row">
        <td class="col-3"><strong>ID </strong></td>
        <td class="col-9"><%= @user.id %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Role </strong></td>
        <td class="col-9"><%= @user.role.capitalize %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Name </strong></td>
        <td class="col-9"><%= @user.name %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Email </strong></td>
        <td class="col-9"><%= @user.email %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Created At </strong></td>
        <td class="col-9"><%= @user.created_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Updated At </strong></td>
        <td class="col-9"><%= @user.updated_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Confirmed At </strong></td>
        <td class="col-9"><%= @user.confirmed_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Last Signed In At </strong></td>
        <td class="col-9"><%= @user.last_sign_in_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Confirmation Sent At </strong></td>
        <td class="col-9"><%= @user.confirmation_sent_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Confirmed At </strong></td>
        <td class="col-9"><%= @user.confirmed_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Current Sign In At </strong></td>
        <td class="col-9"><%= @user.current_sign_in_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Current Sign In At </strong></td>
        <td class="col-9"><%= @user.current_sign_in_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Deleted At </strong></td>
        <td class="col-9"><%= @user.deleted_at %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Sign In Count </strong></td>
        <td class="col-9"><%= @user.sign_in_count %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Last Sign In IP </strong></td>
        <td class="col-9"><%= @user.last_sign_in_ip %></td>
      </tr>

      <tr class="row">
        <td class="col-3"><strong>Current Sign In IP </strong></td>
        <td class="col-9"><%= @user.current_sign_in_ip %></td>
      </tr>

    </tbody>
  </table>
</div>

app/views/users/_user.html.erb
<tr>
  <td width="100" class="middle">
    <div class="media">
      <div class="media-left">
          <%= image_tag user.gravatar, class: "media-object" %>
          <h6 class="text-center">ID: <%= user.id %></h6>
      </div>

      <div class="media-body">
        <% if user.deleted_at %>
          <del><h4 class="media-heading"><%= user.name %></h4></del>
        <% else %>
          <h4 class="media-heading"><%= user.name %></h4>
        <% end %>

        <div class="row">
          <div class="col-6">
            Email: <strong><%= user.email %></strong>
          </div>
          <div class="col-6">
            Role: <strong><%= user.role %></strong>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            Created At: <strong><%= user.created_at %></strong>
          </div>
          <div class="col-6">
            Updated At: <strong><%= user.updated_at %></strong>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            Confirmed At: <strong><%= user.confirmed_at %></strong>
          </div>
          <div class="col-6">
            Last Signed In At: <strong><%= user.last_sign_in_at %></strong>
          </div>
        </div>

      </div>
    </div>
  </td>

  <td width="100" class="middle">
    <div class="media float-right">
      <div class="media-right">
        <%= link_to '<i class="fa fa-info" style="font-size:18px;color:white;"></i>'.html_safe, user, method: "get", class: "btn btn-circle btn-success btn-xs" %>
        <%= link_to '<i class="fa fa-pencil-square-o" style="font-size:18px;color:white"></i>'.html_safe, edit_user_path(user), method: "get", class: "btn btn-circle btn-info btn-xs" %>
        <%= link_to '<i class="fa fa-remove" style="font-size:18px;color:white"></i>'.html_safe, user, class: "btn btn-circle btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </td>
</tr>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'show' %>

<div class="container-fluid">
  <%= simple_form_for(@user) do |f| %>
    <div class="form-inputs">
      <%= f.label :role, required: true, label: "User role:" %>
      <%= f.select(:role, [['Student', 'student'], ['Guardian', 'guardian'], ['Teacher', 'teacher'], ['Admin', 'admin']]) %><br />
    </div>

    <br />

    <div class="form-actions">
      <%= f.button :submit, "Update", class: "btn-primary" %>
    </div>

  <% end %>
</div>

<br />

<div class="row-fluid">
  <%= link_to '<i class="fa fa-info" style="font-size:18px;color:white;"></i>'.html_safe, @user, method: "get", class: "btn btn-circle btn-success btn-xs" %>
  <%= link_to '<i class="fa fa-list" style="font-size:18px;color:white;"></i>'.html_safe, users_path, method: "get", class: "btn btn-circle btn-success btn-xs" %>
  <%= link_to '<i class="fa fa-remove" style="font-size:18px;color:white"></i>'.html_safe, @user, class: "btn btn-circle btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% if @user.deleted_at %>
    <p>Reactivate User? <%= link_to "Reactivate", reactivate_user_path(@user),  method: "patch", class: "btn-outline-danger" %></p>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>
  Users
  <%= form_tag(users_path, class: "form-inline my-2 my-lg-0", role: "search", method: :get) do %>
    <div class="input-group">
      <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2", placeholder: "Search...", autocomplete: "off" %>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </div>
  <% end %>
</h1>

<div class="row-fluid">
  <div class="row">

    <div class="col-2">

      <table class="table table-striped table-hover">

        <tbody>

          <tr>
            <% active = (params[:role] == nil || params[:role].empty?) && !params[:deleted_at] ? 'active' : '' %>
            <%= link_to users_path, class: "list-group-item #{active}" do %>
              All Users <span class="badge badge-light float-right"><%= @users_count %></span>
            <% end %>
          </tr>

          <% @users_by_roles.each do |role, count| %>
            <tr>
              <% active = params[:role] == role ? 'active' : '' %>
              <%= link_to users_path(role: role), class: "list-group-item #{active}" do %>
                <%= role.nil? ? "None " : role.to_s.capitalize + "s " %><span class="badge badge-light float-right"><%= count %></span>
              <% end %>
            </tr>
          <% end %>

          <tr>
            <% active = params[:deleted_at] ? 'active' : '' %>
            <%= link_to users_path(deleted_at: !nil), class: "list-group-item #{active}" do %>
              Deleted <span class="badge badge-light float-right"><%= @deleted_users_count %></span>
            <% end %>
          </tr>

        </tbody>

      </table>

    </div>

    <div class="col-10">

      <% if @users.blank? %>
        <div class="alert alert-warning">
          <strong>Records not found</strong>
        </div>
      <% end %>

      <div class="text-center">
        <%= paginate @users %>
      </div>

      <div class="panel panel-default">
        <table class="table">
          <%= render @users %>
        </table>
      </div>

    </div>

  </div>
</div>

app/views/users/show.html.erb
<h1>Show User <%= @user.name %></h1>

<%= render 'show' %>

<div>
 <%= link_to '<i class="fa fa-list" style="font-size:18px;color:white;"></i>'.html_safe, users_path, method: "get", class: "btn btn-circle btn-success btn-xs" %>
 <%= link_to '<i class="fa fa-pencil-square-o" style="font-size:18px;color:white"></i>'.html_safe, edit_user_path(@user), method: "get", class: "btn btn-circle btn-info btn-xs" %>
 <%= link_to '<i class="fa fa-remove" style="font-size:18px;color:white"></i>'.html_safe, @user, class: "btn btn-circle btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
</div>